import re
import string
import nltk
from textblob import TextBlob
from newspaper import Article
import requests
from bs4 import BeautifulSoup
import unicodedata

# Download required NLTK data
try:
    nltk.download('punkt', quiet=True)
    nltk.download('stopwords', quiet=True)
    nltk.download('wordnet', quiet=True)
except:
    pass

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

class TextPreprocessor:
    def __init__(self):
        self.lemmatizer = WordNetLemmatizer()
        
        # English stopwords
        try:
            self.stop_words = set(stopwords.words('english'))
        except:
            self.stop_words = set()
        
        # Filipino slang dictionary for detection
        self.filipino_slang = {
            # Common Filipino internet slang
            'lol': 'laugh out loud',
            'haha': 'laughter',
            'hehe': 'laughter',
            'hihi': 'laughter',
            'kek': 'laughter',
            'char': 'just kidding',
            'charot': 'just kidding',
            'chos': 'just kidding',
            'chz': 'just kidding',
            'jk': 'just kidding',
            'joke': 'just kidding',
            'sarcasm': 'sarcastic',
            'eme': 'whatever',
            'ganern': 'like that',
            'ganon': 'like that',
            'ganyan': 'like that',
            'yun': 'that',
            'yung': 'the',
            'ung': 'the',
            'ng': 'of',
            'sa': 'in',
            'na': 'already',
            'pa': 'still',
            'lang': 'only',
            'naman': 'anyway',
            'kasi': 'because',
            'pero': 'but',
            'tapos': 'then',
            'saka': 'and',
            'din': 'also',
            'rin': 'also',
            'daw': 'allegedly',
            'raw': 'allegedly',
            'diba': 'right',
            'di': 'not',
            'hindi': 'no',
            'oo': 'yes',
            'opo': 'yes sir/maam',
            'ate': 'older sister',
            'kuya': 'older brother',
            'tita': 'aunt',
            'tito': 'uncle',
            'lola': 'grandmother',
            'lolo': 'grandfather',
            'nanay': 'mother',
            'tatay': 'father',
            'asawa': 'spouse',
            'anak': 'child',
            'kapatid': 'sibling',
            'pinsan': 'cousin',
            'barkada': 'friends',
            'tropa': 'friends',
            'bestie': 'best friend',
            'bff': 'best friend forever',
            'crush': 'romantic interest',
            'jowa': 'boyfriend/girlfriend',
            'syota': 'boyfriend/girlfriend',
            'ex': 'former partner',
            'single': 'not in relationship',
            'taken': 'in relationship',
            'complicated': 'relationship status unclear',
            'ghosting': 'suddenly stop communicating',
            'seen zone': 'read but not replied',
            'friendzone': 'just friends',
            'kilig': 'butterfly feeling',
            'selos': 'jealous',
            'bitter': 'resentful',
            'oa': 'over acting',
            'feelingera': 'pretentious',
            'epal': 'attention seeker',
            'kj': 'kill joy',
            'pakipot': 'playing hard to get',
            'torpe': 'shy in romance',
            'assuming': 'presumptuous',
            'feelingers': 'pretentious',
            'plastik': 'fake person',
            'social climber': 'status seeker',
            'maarte': 'high maintenance',
            'mayabang': 'boastful',
            'yabang': 'boastful',
            'hambog': 'show off',
            'feeling': 'pretending',
            'arte': 'drama',
            'nega': 'negative',
            'toxic': 'harmful',
            'salty': 'bitter',
            'savage': 'brutal',
            'shookt': 'shocked',
            'triggered': 'provoked',
            'pressed': 'bothered',
            'sana all': 'wish everyone',
            'same energy': 'similar vibe',
            'mood': 'feeling',
            'vibe': 'atmosphere',
            'flex': 'show off',
            'lowkey': 'somewhat',
            'highkey': 'obviously',
            'deadass': 'seriously',
            'periodt': 'period',
            'facts': 'truth',
            'tea': 'gossip',
            'spill': 'reveal',
            'drag': 'criticize',
            'roast': 'mock',
            'burn': 'insult',
            'clap back': 'respond sharply',
            'throw shade': 'subtle insult',
            'cancel': 'boycott',
            'stan': 'support strongly',
            'ship': 'support relationship',
            'otp': 'one true pair',
            'bias': 'favorite',
            'ult': 'ultimate favorite',
            'fave': 'favorite',
            'bop': 'good song',
            'slaps': 'excellent',
            'fire': 'amazing',
            'lit': 'exciting',
            'bomb': 'excellent',
            'sick': 'cool',
            'dope': 'cool',
            'tight': 'cool',
            'fresh': 'cool',
            'clean': 'good',
            'smooth': 'good',
            'solid': 'reliable',
            'legit': 'legitimate',
            'real': 'authentic',
            'fake': 'not real',
            'cap': 'lie',
            'no cap': 'no lie',
            'bet': 'okay',
            'say less': 'understood',
            'word': 'agreed',
            'true': 'correct',
            'false': 'incorrect',
            'wrong': 'incorrect',
            'right': 'correct',
            'left': 'departed',
            'ghost': 'disappear',
            'bounce': 'leave',
            'dip': 'leave',
            'peace': 'goodbye',
            'later': 'goodbye',
            'ttyl': 'talk to you later',
            'brb': 'be right back',
            'gtg': 'got to go',
            'omg': 'oh my god',
            'omfg': 'oh my god',
            'wtf': 'what the f',
            'wth': 'what the hell',
            'smh': 'shake my head',
            'fml': 'f my life',
            'yolo': 'you only live once',
            'fomo': 'fear of missing out',
            'imo': 'in my opinion',
            'imho': 'in my humble opinion',
            'tbh': 'to be honest',
            'ngl': 'not gonna lie',
            'irl': 'in real life',
            'irl': 'in real life',
            'dm': 'direct message',
            'pm': 'private message',
            'slide': 'send message',
            'hit up': 'contact',
            'hmu': 'hit me up',
            'wyd': 'what you doing',
            'hbu': 'how about you',
            'sup': 'what\'s up',
            'wassup': 'what\'s up',
            'hey': 'hello',
            'hi': 'hello',
            'yo': 'hello',
            'uy': 'hey',
            'oi': 'hey',
            'pre': 'friend',
            'bro': 'brother',
            'sis': 'sister',
            'dude': 'person',
            'man': 'person',
            'girl': 'female',
            'boy': 'male',
            'guy': 'male',
            'gal': 'female',
            'peeps': 'people',
            'fam': 'family',
            'squad': 'group',
            'crew': 'group',
            'gang': 'group',
            'team': 'group',
            'homie': 'friend',
            'buddy': 'friend',
            'pal': 'friend',
            'mate': 'friend',
            'amigo': 'friend',
            'champ': 'champion',
            'boss': 'leader',
            'chief': 'leader',
            'captain': 'leader',
            'king': 'ruler',
            'queen': 'ruler',
            'prince': 'royalty',
            'princess': 'royalty',
            'god': 'deity',
            'goddess': 'deity',
            'angel': 'heavenly being',
            'devil': 'evil being',
            'demon': 'evil being',
            'monster': 'creature',
            'beast': 'animal',
            'animal': 'creature',
            'human': 'person',
            'alien': 'extraterrestrial',
            'robot': 'machine',
            'cyborg': 'part machine',
            'zombie': 'undead',
            'vampire': 'blood drinker',
            'ghost': 'spirit',
            'spirit': 'soul',
            'soul': 'essence',
            'heart': 'emotion center',
            'mind': 'thinking center',
            'brain': 'thinking organ',
            'head': 'top body part',
            'face': 'front of head',
            'eye': 'seeing organ',
            'nose': 'smelling organ',
            'mouth': 'eating organ',
            'ear': 'hearing organ',
            'hand': 'grasping appendage',
            'foot': 'walking appendage',
            'body': 'physical form',
            'life': 'existence',
            'death': 'end of life',
            'birth': 'beginning of life',
            'love': 'affection',
            'hate': 'dislike',
            'like': 'enjoy',
            'dislike': 'not enjoy',
            'want': 'desire',
            'need': 'require',
            'have': 'possess',
            'get': 'obtain',
            'give': 'provide',
            'take': 'receive',
            'make': 'create',
            'do': 'perform',
            'go': 'move',
            'come': 'arrive',
            'see': 'view',
            'hear': 'listen',
            'say': 'speak',
            'tell': 'inform',
            'know': 'understand',
            'think': 'consider',
            'feel': 'sense',
            'look': 'observe',
            'find': 'discover',
            'work': 'labor',
            'play': 'have fun',
            'run': 'move fast',
            'walk': 'move slowly',
            'sit': 'rest',
            'stand': 'upright',
            'sleep': 'rest',
            'wake': 'become alert',
            'eat': 'consume food',
            'drink': 'consume liquid',
            'read': 'view text',
            'write': 'create text',
            'learn': 'gain knowledge',
            'teach': 'share knowledge',
            'help': 'assist',
            'hurt': 'harm',
            'heal': 'cure',
            'fix': 'repair',
            'break': 'damage',
            'build': 'construct',
            'destroy': 'demolish',
            'create': 'make',
            'delete': 'remove',
            'add': 'include',
            'remove': 'exclude',
            'put': 'place',
            'pull': 'draw',
            'push': 'shove',
            'open': 'unlock',
            'close': 'shut',
            'start': 'begin',
            'stop': 'end',
            'continue': 'keep going',
            'finish': 'complete',
            'win': 'succeed',
            'lose': 'fail',
            'try': 'attempt',
            'succeed': 'achieve',
            'fail': 'not succeed',
            'pass': 'succeed',
            'fail': 'not pass',
            'good': 'positive',
            'bad': 'negative',
            'great': 'excellent',
            'terrible': 'awful',
            'amazing': 'wonderful',
            'horrible': 'terrible',
            'beautiful': 'attractive',
            'ugly': 'unattractive',
            'smart': 'intelligent',
            'stupid': 'unintelligent',
            'funny': 'humorous',
            'boring': 'uninteresting',
            'interesting': 'engaging',
            'exciting': 'thrilling',
            'scary': 'frightening',
            'safe': 'secure',
            'dangerous': 'risky',
            'easy': 'simple',
            'hard': 'difficult',
            'simple': 'uncomplicated',
            'complex': 'complicated',
            'big': 'large',
            'small': 'little',
            'huge': 'enormous',
            'tiny': 'minuscule',
            'long': 'extended',
            'short': 'brief',
            'tall': 'high',
            'low': 'short',
            'wide': 'broad',
            'narrow': 'thin',
            'thick': 'wide',
            'thin': 'narrow',
            'fat': 'overweight',
            'skinny': 'underweight',
            'heavy': 'weighty',
            'light': 'not heavy',
            'fast': 'quick',
            'slow': 'not fast',
            'hot': 'warm',
            'cold': 'cool',
            'warm': 'heated',
            'cool': 'chilled',
            'wet': 'moist',
            'dry': 'not wet',
            'clean': 'not dirty',
            'dirty': 'not clean',
            'new': 'recent',
            'old': 'aged',
            'young': 'youthful',
            'fresh': 'new',
            'stale': 'old',
            'rich': 'wealthy',
            'poor': 'not wealthy',
            'cheap': 'inexpensive',
            'expensive': 'costly',
            'free': 'no cost',
            'busy': 'occupied',
            'lazy': 'inactive',
            'active': 'energetic',
            'tired': 'exhausted',
            'awake': 'alert',
            'asleep': 'sleeping',
            'alive': 'living',
            'dead': 'not alive',
            'healthy': 'well',
            'sick': 'ill',
            'strong': 'powerful',
            'weak': 'not strong',
            'brave': 'courageous',
            'scared': 'afraid',
            'happy': 'joyful',
            'sad': 'unhappy',
            'angry': 'mad',
            'calm': 'peaceful',
            'excited': 'enthusiastic',
            'bored': 'uninterested',
            'surprised': 'shocked',
            'confused': 'puzzled',
            'sure': 'certain',
            'unsure': 'uncertain',
            'ready': 'prepared',
            'unready': 'unprepared',
            'careful': 'cautious',
            'careless': 'reckless',
            'patient': 'tolerant',
            'impatient': 'intolerant',
            'kind': 'nice',
            'mean': 'cruel',
            'friendly': 'nice',
            'unfriendly': 'hostile',
            'polite': 'courteous',
            'rude': 'impolite',
            'honest': 'truthful',
            'dishonest': 'lying',
            'loyal': 'faithful',
            'disloyal': 'unfaithful',
            'generous': 'giving',
            'selfish': 'self-centered',
            'humble': 'modest',
            'proud': 'arrogant',
            'confident': 'self-assured',
            'shy': 'timid',
            'outgoing': 'social',
            'introverted': 'reserved',
            'extroverted': 'outgoing',
            'serious': 'grave',
            'playful': 'fun',
            'mature': 'grown-up',
            'immature': 'childish',
            'responsible': 'accountable',
            'irresponsible': 'unreliable',
            'reliable': 'dependable',
            'unreliable': 'undependable',
            'trustworthy': 'reliable',
            'untrustworthy': 'unreliable',
            'creative': 'imaginative',
            'uncreative': 'unimaginative',
            'artistic': 'creative',
            'logical': 'rational',
            'illogical': 'irrational',
            'practical': 'realistic',
            'impractical': 'unrealistic',
            'organized': 'orderly',
            'disorganized': 'messy',
            'neat': 'tidy',
            'messy': 'untidy',
            'punctual': 'on time',
            'late': 'tardy',
            'early': 'ahead of time',
            'flexible': 'adaptable',
            'inflexible': 'rigid',
            'open-minded': 'receptive',
            'close-minded': 'narrow',
            'optimistic': 'positive',
            'pessimistic': 'negative',
            'realistic': 'practical',
            'idealistic': 'unrealistic',
            'ambitious': 'driven',
            'unambitious': 'complacent',
            'motivated': 'driven',
            'unmotivated': 'lazy',
            'determined': 'resolute',
            'indecisive': 'uncertain',
            'decisive': 'firm',
            'independent': 'self-reliant',
            'dependent': 'reliant',
            'leader': 'guide',
            'follower': 'supporter',
            'teacher': 'educator',
            'student': 'learner',
            'worker': 'employee',
            'boss': 'supervisor',
            'customer': 'client',
            'seller': 'vendor',
            'buyer': 'purchaser',
            'owner': 'proprietor',
            'renter': 'tenant',
            'neighbor': 'adjacent resident',
            'stranger': 'unknown person',
            'acquaintance': 'known person',
            'colleague': 'coworker',
            'partner': 'associate',
            'competitor': 'rival',
            'enemy': 'foe',
            'ally': 'supporter',
            'helper': 'assistant',
            'supporter': 'backer',
            'opponent': 'adversary',
            'critic': 'reviewer',
            'fan': 'admirer',
            'celebrity': 'famous person',
            'expert': 'specialist',
            'amateur': 'beginner',
            'professional': 'expert',
            'volunteer': 'unpaid helper',
            'visitor': 'guest',
            'host': 'entertainer',
            'guest': 'visitor',
            'member': 'participant',
            'outsider': 'non-member',
            'insider': 'member',
            'local': 'resident',
            'tourist': 'visitor',
            'native': 'indigenous',
            'foreigner': 'alien',
            'citizen': 'national',
            'immigrant': 'newcomer',
            'refugee': 'displaced person',
            'resident': 'inhabitant',
            'inhabitant': 'dweller',
            'population': 'people',
            'community': 'group',
            'society': 'civilization',
            'culture': 'way of life',
            'tradition': 'custom',
            'custom': 'practice',
            'habit': 'routine',
            'routine': 'regular activity',
            'schedule': 'timetable',
            'plan': 'strategy',
            'goal': 'objective',
            'dream': 'aspiration',
            'wish': 'desire',
            'hope': 'expectation',
            'fear': 'anxiety',
            'worry': 'concern',
            'stress': 'pressure',
            'pressure': 'force',
            'problem': 'issue',
            'solution': 'answer',
            'question': 'inquiry',
            'answer': 'response',
            'idea': 'concept',
            'thought': 'idea',
            'opinion': 'view',
            'belief': 'conviction',
            'fact': 'truth',
            'lie': 'falsehood',
            'truth': 'reality',
            'reality': 'actuality',
            'fantasy': 'imagination',
            'dream': 'vision',
            'nightmare': 'bad dream',
            'memory': 'recollection',
            'experience': 'encounter',
            'adventure': 'exciting experience',
            'journey': 'trip',
            'trip': 'travel',
            'vacation': 'holiday',
            'holiday': 'celebration',
            'celebration': 'party',
            'party': 'gathering',
            'meeting': 'assembly',
            'conference': 'formal meeting',
            'event': 'occurrence',
            'occasion': 'event',
            'moment': 'instant',
            'time': 'duration',
            'hour': 'sixty minutes',
            'minute': 'sixty seconds',
            'second': 'moment',
            'day': 'twenty-four hours',
            'night': 'dark period',
            'morning': 'early day',
            'afternoon': 'mid day',
            'evening': 'late day',
            'week': 'seven days',
            'month': 'thirty days',
            'year': 'twelve months',
            'decade': 'ten years',
            'century': 'hundred years',
            'millennium': 'thousand years',
            'past': 'before now',
            'present': 'now',
            'future': 'after now',
            'today': 'this day',
            'yesterday': 'previous day',
            'tomorrow': 'next day',
            'now': 'at this moment',
            'then': 'at that time',
            'soon': 'in near future',
            'later': 'in future',
            'never': 'not ever',
            'always': 'every time',
            'sometimes': 'occasionally',
            'often': 'frequently',
            'rarely': 'seldom',
            'usually': 'normally',
            'normally': 'typically',
            'typically': 'usually',
            'generally': 'mostly',
            'mostly': 'mainly',
            'mainly': 'primarily',
            'primarily': 'chiefly',
            'chiefly': 'mainly',
            'especially': 'particularly',
            'particularly': 'especially',
            'specifically': 'precisely',
            'precisely': 'exactly',
            'exactly': 'precisely',
            'approximately': 'about',
            'about': 'approximately',
            'around': 'approximately',
            'nearly': 'almost',
            'almost': 'nearly',
            'quite': 'rather',
            'rather': 'somewhat',
            'somewhat': 'a bit',
            'very': 'extremely',
            'extremely': 'very',
            'really': 'truly',
            'truly': 'really',
            'actually': 'in fact',
            'definitely': 'certainly',
            'certainly': 'definitely',
            'probably': 'likely',
            'likely': 'probably',
            'possibly': 'maybe',
            'maybe': 'perhaps',
            'perhaps': 'maybe',
            'obviously': 'clearly',
            'clearly': 'obviously',
            'apparently': 'seemingly',
            'seemingly': 'apparently',
            'supposedly': 'allegedly',
            'allegedly': 'supposedly',
            'reportedly': 'according to reports',
            'according': 'as stated by',
            'basically': 'fundamentally',
            'fundamentally': 'essentially',
            'essentially': 'basically',
            'literally': 'actually',
            'figuratively': 'metaphorically',
            'metaphorically': 'symbolically',
            'symbolically': 'representatively',
            'technically': 'strictly speaking',
            'officially': 'formally',
            'formally': 'officially',
            'informally': 'casually',
            'casually': 'informally',
            'seriously': 'genuinely',
            'genuinely': 'sincerely',
            'sincerely': 'honestly',
            'honestly': 'truthfully',
            'frankly': 'candidly',
            'candidly': 'openly',
            'openly': 'publicly',
            'publicly': 'openly',
            'privately': 'personally',
            'personally': 'individually',
            'individually': 'separately',
            'separately': 'apart',
            'together': 'jointly',
            'jointly': 'collectively',
            'collectively': 'as a group',
            'alone': 'by oneself',
            'solo': 'alone',
            'single': 'one',
            'double': 'two',
            'triple': 'three',
            'multiple': 'many',
            'several': 'some',
            'few': 'not many',
            'many': 'numerous',
            'numerous': 'many',
            'countless': 'innumerable',
            'infinite': 'endless',
            'endless': 'infinite',
            'limited': 'restricted',
            'unlimited': 'unrestricted',
            'restricted': 'limited',
            'unrestricted': 'free',
            'free': 'unrestricted',
            'bound': 'tied',
            'tied': 'connected',
            'connected': 'linked',
            'linked': 'joined',
            'joined': 'united',
            'united': 'together',
            'divided': 'separated',
            'separated': 'apart',
            'apart': 'separate',
            'close': 'near',
            'near': 'close',
            'far': 'distant',
            'distant': 'remote',
            'remote': 'far away',
            'here': 'this place',
            'there': 'that place',
            'where': 'what place',
            'everywhere': 'all places',
            'nowhere': 'no place',
            'somewhere': 'some place',
            'anywhere': 'any place',
            'inside': 'within',
            'outside': 'beyond',
            'within': 'inside',
            'beyond': 'past',
            'above': 'over',
            'below': 'under',
            'over': 'above',
            'under': 'below',
            'beside': 'next to',
            'behind': 'back of',
            'front': 'forward',
            'back': 'rear',
            'forward': 'ahead',
            'backward': 'reverse',
            'up': 'upward',
            'down': 'downward',
            'left': 'leftward',
            'right': 'rightward',
            'straight': 'direct',
            'curved': 'bent',
            'bent': 'curved',
            'round': 'circular',
            'square': 'rectangular',
            'flat': 'level',
            'steep': 'sharp incline',
            'smooth': 'even',
            'rough': 'uneven',
            'sharp': 'pointed',
            'dull': 'blunt',
            'bright': 'luminous',
            'dark': 'dim',
            'light': 'bright',
            'heavy': 'weighty',
            'empty': 'vacant',
            'full': 'complete',
            'half': 'partial',
            'whole': 'complete',
            'part': 'portion',
            'piece': 'fragment',
            'bit': 'small piece',
            'chunk': 'large piece',
            'slice': 'thin piece',
            'section': 'part',
            'segment': 'section',
            'division': 'separation',
            'category': 'classification',
            'type': 'kind',
            'kind': 'type',
            'sort': 'type',
            'variety': 'type',
            'brand': 'make',
            'model': 'version',
            'version': 'edition',
            'edition': 'version',
            'copy': 'duplicate',
            'original': 'first',
            'first': 'initial',
            'last': 'final',
            'final': 'last',
            'next': 'following',
            'previous': 'before',
            'before': 'prior',
            'after': 'following',
            'during': 'while',
            'while': 'during',
            'until': 'up to',
            'since': 'from then',
            'from': 'starting at',
            'to': 'toward',
            'toward': 'in direction of',
            'through': 'via',
            'via': 'by way of',
            'across': 'over',
            'along': 'beside',
            'around': 'surrounding',
            'between': 'among',
            'among': 'between',
            'with': 'together with',
            'without': 'lacking',
            'including': 'containing',
            'excluding': 'not including',
            'except': 'excluding',
            'besides': 'in addition to',
            'plus': 'and',
            'minus': 'without',
            'times': 'multiplied by',
            'divided': 'split',
            'equal': 'same',
            'unequal': 'different',
            'same': 'identical',
            'different': 'unlike',
            'similar': 'alike',
            'unlike': 'different',
            'like': 'similar to',
            'as': 'like',
            'than': 'compared to',
            'more': 'greater',
            'less': 'fewer',
            'most': 'greatest',
            'least': 'smallest',
            'best': 'finest',
            'worst': 'poorest',
            'better': 'superior',
            'worse': 'inferior',
            'superior': 'better',
            'inferior': 'worse',
            'perfect': 'flawless',
            'imperfect': 'flawed',
            'complete': 'finished',
            'incomplete': 'unfinished',
            'finished': 'done',
            'unfinished': 'incomplete',
            'done': 'completed',
            'undone': 'not done',
            'ready': 'prepared',
            'unready': 'unprepared',
            'prepared': 'ready',
            'unprepared': 'not ready',
            'available': 'accessible',
            'unavailable': 'not available',
            'accessible': 'reachable',
            'inaccessible': 'unreachable',
            'possible': 'feasible',
            'impossible': 'not possible',
            'probable': 'likely',
            'improbable': 'unlikely',
            'certain': 'sure',
            'uncertain': 'unsure',
            'clear': 'obvious',
            'unclear': 'vague',
            'obvious': 'evident',
            'hidden': 'concealed',
            'visible': 'seen',
            'invisible': 'unseen',
            'open': 'accessible',
            'closed': 'shut',
            'public': 'open',
            'private': 'personal',
            'secret': 'hidden',
            'known': 'familiar',
            'unknown': 'unfamiliar',
            'familiar': 'known',
            'unfamiliar': 'strange',
            'strange': 'odd',
            'normal': 'usual',
            'unusual': 'strange',
            'common': 'ordinary',
            'uncommon': 'rare',
            'rare': 'uncommon',
            'special': 'unique',
            'ordinary': 'normal',
            'extraordinary': 'remarkable',
            'remarkable': 'notable',
            'notable': 'significant',
            'significant': 'important',
            'important': 'significant',
            'unimportant': 'trivial',
            'trivial': 'minor',
            'major': 'significant',
            'minor': 'small',
            'main': 'primary',
            'secondary': 'second',
            'primary': 'first',
            'basic': 'fundamental',
            'advanced': 'sophisticated',
            'simple': 'easy',
            'complicated': 'complex',
            'complex': 'complicated',
            'detailed': 'thorough',
            'brief': 'short',
            'long': 'extended',
            'short': 'brief',
            'quick': 'fast',
            'slow': 'gradual',
            'sudden': 'abrupt',
            'gradual': 'slow',
            'immediate': 'instant',
            'delayed': 'postponed',
            'early': 'ahead of time',
            'late': 'behind time',
            'on time': 'punctual',
            'frequent': 'regular',
            'infrequent': 'rare',
            'regular': 'consistent',
            'irregular': 'inconsistent',
            'consistent': 'steady',
            'inconsistent': 'variable',
            'steady': 'stable',
            'unsteady': 'unstable',
            'stable': 'firm',
            'unstable': 'shaky',
            'firm': 'solid',
            'soft': 'gentle',
            'hard': 'difficult',
            'gentle': 'mild',
            'harsh': 'severe',
            'mild': 'gentle',
            'severe': 'harsh',
            'strict': 'rigid',
            'loose': 'relaxed',
            'tight': 'secure',
            'relaxed': 'calm',
            'tense': 'stressed',
            'calm': 'peaceful',
            'chaotic': 'disorderly',
            'peaceful': 'tranquil',
            'violent': 'aggressive',
            'aggressive': 'hostile',
            'passive': 'inactive',
            'active': 'energetic',
            'energetic': 'lively',
            'lively': 'vibrant',
            'dull': 'boring',
            'exciting': 'thrilling',
            'thrilling': 'exciting',
            'boring': 'tedious',
            'interesting': 'engaging',
            'engaging': 'captivating',
            'captivating': 'fascinating',
            'fascinating': 'intriguing',
            'intriguing': 'mysterious',
            'mysterious': 'puzzling',
            'puzzling': 'confusing',
            'confusing': 'unclear',
            'clear': 'understandable',
            'understandable': 'comprehensible',
            'comprehensible': 'clear',
            'incomprehensible': 'unclear',
            'logical': 'reasonable',
            'illogical': 'unreasonable',
            'reasonable': 'sensible',
            'unreasonable': 'irrational',
            'rational': 'logical',
            'irrational': 'illogical',
            'sensible': 'wise',
            'foolish': 'unwise',
            'wise': 'intelligent',
            'unwise': 'foolish',
            'intelligent': 'smart',
            'unintelligent': 'stupid',
            'smart': 'clever',
            'stupid': 'dumb',
            'clever': 'bright',
            'dumb': 'stupid',
            'bright': 'intelligent',
            'brilliant': 'genius',
            'genius': 'brilliant',
            'talented': 'gifted',
            'gifted': 'talented',
            'skilled': 'expert',
            'unskilled': 'amateur',
            'expert': 'professional',
            'amateur': 'beginner',
            'beginner': 'novice',
            'novice': 'beginner',
            'experienced': 'seasoned',
            'inexperienced': 'new',
            'new': 'fresh',
            'old': 'aged',
            'young': 'youthful',
            'aged': 'elderly',
            'elderly': 'old',
            'adult': 'grown-up',
            'child': 'kid',
            'baby': 'infant',
            'teenager': 'adolescent',
            'adolescent': 'teen',
            'teen': 'teenager',
            'senior': 'elder',
            'junior': 'younger',
            'older': 'senior',
            'younger': 'junior',
            'elder': 'senior',
            'ancestor': 'forefather',
            'descendant': 'offspring',
            'parent': 'guardian',
            'child': 'offspring',
            'sibling': 'brother or sister',
            'relative': 'family member',
            'family': 'relatives',
            'household': 'family unit',
            'home': 'residence',
            'house': 'dwelling',
            'apartment': 'flat',
            'room': 'chamber',
            'kitchen': 'cooking area',
            'bedroom': 'sleeping area',
            'bathroom': 'washroom',
            'living room': 'lounge',
            'dining room': 'eating area',
            'office': 'workplace',
            'school': 'educational institution',
            'hospital': 'medical facility',
            'store': 'shop',
            'restaurant': 'eatery',
            'hotel': 'lodging',
            'bank': 'financial institution',
            'library': 'book repository',
            'museum': 'exhibition hall',
            'theater': 'performance venue',
            'cinema': 'movie theater',
            'park': 'recreational area',
            'beach': 'shoreline',
            'mountain': 'peak',
            'forest': 'woods',
            'desert': 'arid land',
            'ocean': 'sea',
            'river': 'waterway',
            'lake': 'body of water',
            'city': 'urban area',
            'town': 'small city',
            'village': 'small town',
            'country': 'nation',
            'state': 'province',
            'region': 'area',
            'continent': 'landmass',
            'world': 'earth',
            'planet': 'celestial body',
            'universe': 'cosmos',
            'space': 'outer space',
            'sky': 'heavens',
            'cloud': 'vapor mass',
            'rain': 'precipitation',
            'snow': 'frozen precipitation',
            'sun': 'star',
            'moon': 'satellite',
            'star': 'celestial light',
            'wind': 'air movement',
            'storm': 'bad weather',
            'weather': 'atmospheric conditions',
            'climate': 'weather pattern',
            'season': 'time period',
            'spring': 'renewal season',
            'summer': 'hot season',
            'autumn': 'fall season',
            'winter': 'cold season',
            'temperature': 'heat level',
            'degree': 'unit of measurement',
            'measurement': 'quantification',
            'size': 'dimension',
            'weight': 'mass',
            'height': 'vertical dimension',
            'width': 'horizontal dimension',
            'length': 'linear dimension',
            'distance': 'space between',
            'speed': 'velocity',
            'direction': 'course',
            'location': 'position',
            'place': 'location',
            'position': 'placement',
            'situation': 'circumstance',
            'condition': 'state',
            'state': 'condition',
            'status': 'standing',
            'level': 'degree',
            'grade': 'level',
            'class': 'category',
            'group': 'collection',
            'team': 'group',
            'organization': 'institution',
            'company': 'business',
            'business': 'enterprise',
            'industry': 'sector',
            'market': 'marketplace',
            'economy': 'financial system',
            'money': 'currency',
            'price': 'cost',
            'value': 'worth',
            'profit': 'gain',
            'loss': 'deficit',
            'income': 'earnings',
            'expense': 'cost',
            'budget': 'financial plan',
            'investment': 'financial commitment',
            'savings': 'stored money',
            'debt': 'owed money',
            'loan': 'borrowed money',
            'credit': 'borrowed funds',
            'payment': 'remittance',
            'purchase': 'buying',
            'sale': 'selling',
            'trade': 'exchange',
            'exchange': 'swap',
            'deal': 'agreement',
            'contract': 'agreement',
            'agreement': 'accord',
            'promise': 'commitment',
            'commitment': 'obligation',
            'responsibility': 'duty',
            'duty': 'obligation',
            'job': 'work',
            'career': 'profession',
            'profession': 'occupation',
            'occupation': 'job',
            'task': 'assignment',
            'assignment': 'task',
            'project': 'undertaking',
            'mission': 'objective',
            'objective': 'goal',
            'purpose': 'intention',
            'intention': 'aim',
            'aim': 'target',
            'target': 'objective',
            'result': 'outcome',
            'outcome': 'result',
            'consequence': 'result',
            'effect': 'result',
            'cause': 'reason',
            'reason': 'explanation',
            'explanation': 'clarification',
            'description': 'account',
            'account': 'report',
            'report': 'statement',
            'statement': 'declaration',
            'declaration': 'announcement',
            'announcement': 'notice',
            'notice': 'warning',
            'warning': 'alert',
            'alert': 'notification',
            'message': 'communication',
            'communication': 'contact',
            'contact': 'connection',
            'connection': 'link',
            'relationship': 'association',
            'association': 'connection',
            'friendship': 'companionship',
            'companionship': 'fellowship',
            'partnership': 'collaboration',
            'collaboration': 'cooperation',
            'cooperation': 'teamwork',
            'teamwork': 'collaboration',
            'competition': 'contest',
            'contest': 'competition',
            'game': 'sport',
            'sport': 'athletic activity',
            'activity': 'action',
            'action': 'deed',
            'deed': 'act',
            'act': 'action',
            'behavior': 'conduct',
            'conduct': 'behavior',
            'attitude': 'disposition',
            'disposition': 'temperament',
            'temperament': 'nature',
            'nature': 'character',
            'character': 'personality',
            'personality': 'individuality',
            'individuality': 'uniqueness',
            'uniqueness': 'distinctiveness',
            'identity': 'self',
            'self': 'individual',
            'individual': 'person',
            'person': 'human being',
            'being': 'existence',
            'existence': 'presence',
            'presence': 'attendance',
            'absence': 'non-presence',
            'attendance': 'presence',
            'participation': 'involvement',
            'involvement': 'engagement',
            'engagement': 'participation',
            'interest': 'curiosity',
            'curiosity': 'inquisitiveness',
            'attention': 'focus',
            'focus': 'concentration',
            'concentration': 'attention',
            'distraction': 'interruption',
            'interruption': 'disruption',
            'disruption': 'disturbance',
            'disturbance': 'interference',
            'interference': 'obstruction',
            'obstruction': 'blockage',
            'blockage': 'barrier',
            'barrier': 'obstacle',
            'obstacle': 'hindrance',
            'hindrance': 'impediment',
            'impediment': 'obstruction',
            'difficulty': 'challenge',
            'challenge': 'test',
            'test': 'examination',
            'examination': 'inspection',
            'inspection': 'review',
            'review': 'evaluation',
            'evaluation': 'assessment',
            'assessment': 'appraisal',
            'appraisal': 'evaluation',
            'judgment': 'decision',
            'decision': 'choice',
            'choice': 'option',
            'option': 'alternative',
            'alternative': 'substitute',
            'substitute': 'replacement',
            'replacement': 'substitute',
            'change': 'alteration',
            'alteration': 'modification',
            'modification': 'adjustment',
            'adjustment': 'adaptation',
            'adaptation': 'accommodation',
            'accommodation': 'adjustment',
            'improvement': 'enhancement',
            'enhancement': 'betterment',
            'betterment': 'improvement',
            'progress': 'advancement',
            'advancement': 'development',
            'development': 'growth',
            'growth': 'expansion',
            'expansion': 'enlargement',
            'enlargement': 'increase',
            'increase': 'rise',
            'rise': 'ascent',
            'ascent': 'climb',
            'climb': 'ascent',
            'descent': 'decline',
            'decline': 'decrease',
            'decrease': 'reduction',
            'reduction': 'cut',
            'cut': 'reduction',
            'addition': 'supplement',
            'supplement': 'addition',
            'subtraction': 'removal',
            'removal': 'elimination',
            'elimination': 'deletion',
            'deletion': 'removal',
            'creation': 'formation',
            'formation': 'establishment',
            'establishment': 'foundation',
            'foundation': 'basis',
            'basis': 'foundation',
            'structure': 'framework',
            'framework': 'structure',
            'system': 'organization',
            'organization': 'arrangement',
            'arrangement': 'organization',
            'order': 'sequence',
            'sequence': 'series',
            'series': 'succession',
            'succession': 'sequence',
            'pattern': 'design',
            'design': 'plan',
            'plan': 'scheme',
            'scheme': 'strategy',
            'strategy': 'approach',
            'approach': 'method',
            'method': 'technique',
            'technique': 'procedure',
            'procedure': 'process',
            'process': 'operation',
            'operation': 'function',
            'function': 'purpose',
            'use': 'application',
            'application': 'usage',
            'usage': 'utilization',
            'utilization': 'employment',
            'employment': 'use',
            'tool': 'instrument',
            'instrument': 'device',
            'device': 'apparatus',
            'apparatus': 'equipment',
            'equipment': 'gear',
            'gear': 'equipment',
            'machine': 'device',
            'technology': 'innovation',
            'innovation': 'invention',
            'invention': 'creation',
            'discovery': 'finding',
            'finding': 'discovery',
            'research': 'investigation',
            'investigation': 'inquiry',
            'inquiry': 'question',
            'study': 'examination',
            'analysis': 'examination',
            'examination': 'study',
            'observation': 'watching',
            'watching': 'observing',
            'monitoring': 'tracking',
            'tracking': 'following',
            'following': 'pursuing',
            'pursuing': 'chasing',
            'chasing': 'hunting',
            'hunting': 'searching',
            'searching': 'looking',
            'looking': 'seeking',
            'seeking': 'searching',
            'finding': 'locating',
            'locating': 'positioning',
            'positioning': 'placing',
            'placing': 'putting',
            'putting': 'setting',
            'setting': 'placing',
            'getting': 'obtaining',
            'obtaining': 'acquiring',
            'acquiring': 'gaining',
            'gaining': 'earning',
            'earning': 'making',
            'making': 'creating',
            'creating': 'producing',
            'producing': 'generating',
            'generating': 'creating',
            'building': 'constructing',
            'constructing': 'assembling',
            'assembling': 'putting together',
            'destroying': 'demolishing',
            'demolishing': 'tearing down',
            'breaking': 'damaging',
            'damaging': 'harming',
            'harming': 'injuring',
            'injuring': 'hurting',
            'hurting': 'causing pain',
            'healing': 'curing',
            'curing': 'treating',
            'treating': 'caring for',
            'caring': 'looking after',
            'protecting': 'defending',
            'defending': 'guarding',
            'guarding': 'watching over',
            'attacking': 'assaulting',
            'assaulting': 'attacking',
            'fighting': 'battling',
            'battling': 'struggling',
            'struggling': 'striving',
            'striving': 'trying hard',
            'trying': 'attempting',
            'attempting': 'endeavoring',
            'endeavoring': 'striving',
            'succeeding': 'achieving',
            'achieving': 'accomplishing',
            'accomplishing': 'completing',
            'completing': 'finishing',
            'finishing': 'ending',
            'ending': 'concluding',
            'concluding': 'finalizing',
            'finalizing': 'completing',
            'beginning': 'starting',
            'starting': 'commencing',
            'commencing': 'initiating',
            'initiating': 'beginning',
            'continuing': 'proceeding',
            'proceeding': 'advancing',
            'advancing': 'moving forward',
            'moving': 'shifting',
            'shifting': 'changing position',
            'staying': 'remaining',
            'remaining': 'staying',
            'leaving': 'departing',
            'departing': 'going away',
            'arriving': 'coming',
            'coming': 'approaching',
            'approaching': 'nearing',
            'nearing': 'getting close',
            'reaching': 'arriving at',
            'entering': 'going in',
            'exiting': 'going out',
            'returning': 'coming back',
            'visiting': 'calling on',
            'meeting': 'encountering',
            'encountering': 'meeting',
            'greeting': 'welcoming',
            'welcoming': 'receiving',
            'receiving': 'getting',
            'giving': 'providing',
            'providing': 'supplying',
            'supplying': 'furnishing',
            'furnishing': 'providing',
            'offering': 'presenting',
            'presenting': 'showing',
            'showing': 'displaying',
            'displaying': 'exhibiting',
            'exhibiting': 'demonstrating',
            'demonstrating': 'proving',
            'proving': 'establishing',
            'establishing': 'setting up',
            'setting up': 'arranging',
            'arranging': 'organizing',
            'organizing': 'structuring',
            'structuring': 'arranging',
            'planning': 'preparing',
            'preparing': 'getting ready',
            'practicing': 'rehearsing',
            'rehearsing': 'practicing',
            'performing': 'executing',
            'executing': 'carrying out',
            'carrying out': 'implementing',
            'implementing': 'putting into practice',
            'applying': 'using',
            'using': 'employing',
            'employing': 'utilizing',
            'operating': 'running',
            'running': 'managing',
            'managing': 'controlling',
            'controlling': 'directing',
            'directing': 'guiding',
            'guiding': 'leading',
            'leading': 'heading',
            'heading': 'going toward',
            'following': 'coming after',
            'supporting': 'backing',
            'backing': 'supporting',
            'opposing': 'resisting',
            'resisting': 'fighting against',
            'agreeing': 'concurring',
            'concurring': 'agreeing',
            'disagreeing': 'differing',
            'differing': 'varying',
            'varying': 'changing',
            'changing': 'altering',
            'altering': 'modifying',
            'modifying': 'adjusting',
            'adjusting': 'adapting',
            'adapting': 'accommodating',
            'accommodating': 'adjusting to',
            'accepting': 'receiving',
            'receiving': 'taking',
            'taking': 'grasping',
            'grasping': 'understanding',
            'understanding': 'comprehending',
            'comprehending': 'grasping',
            'learning': 'acquiring knowledge',
            'teaching': 'instructing',
            'instructing': 'educating',
            'educating': 'training',
            'training': 'preparing',
            'preparing': 'making ready',
            'studying': 'learning',
            'reading': 'perusing',
            'perusing': 'examining',
            'examining': 'inspecting',
            'inspecting': 'checking',
            'checking': 'verifying',
            'verifying': 'confirming',
            'confirming': 'validating',
            'validating': 'verifying',
            'testing': 'examining',
            'measuring': 'quantifying',
            'quantifying': 'measuring',
            'counting': 'numbering',
            'numbering': 'counting',
            'calculating': 'computing',
            'computing': 'calculating',
            'estimating': 'approximating',
            'approximating': 'estimating',
            'guessing': 'estimating',
            'predicting': 'forecasting',
            'forecasting': 'predicting',
            'expecting': 'anticipating',
            'anticipating': 'expecting',
            'hoping': 'wishing',
            'wishing': 'desiring',
            'desiring': 'wanting',
            'wanting': 'needing',
            'needing': 'requiring',
            'requiring': 'demanding',
            'demanding': 'insisting',
            'insisting': 'requiring',
            'requesting': 'asking',
            'asking': 'inquiring',
            'inquiring': 'questioning',
            'questioning': 'interrogating',
            'interrogating': 'questioning',
            'answering': 'responding',
            'responding': 'replying',
            'replying': 'answering',
            'explaining': 'clarifying',
            'clarifying': 'explaining',
            'describing': 'depicting',
            'depicting': 'portraying',
            'portraying': 'representing',
            'representing': 'symbolizing',
            'symbolizing': 'standing for',
            'meaning': 'signifying',
            'signifying': 'indicating',
            'indicating': 'showing',
            'pointing': 'indicating',
            'directing': 'pointing',
            'aiming': 'targeting',
            'targeting': 'aiming at'
        }
        
        # Sarcasm indicators
        self.sarcasm_indicators = [
            'yeah right', 'sure thing', 'of course', 'obviously',
            'totally', 'absolutely', 'definitely', 'certainly',
            'wow', 'amazing', 'incredible', 'unbelievable',
            'great job', 'well done', 'congratulations', 'bravo',
            'perfect', 'excellent', 'wonderful', 'fantastic'
        ]
        
        # Fake news indicators
        self.fake_news_indicators = [
            'breaking:', 'urgent:', 'shocking:', 'exposed:',
            'you won\'t believe', 'doctors hate', 'this one trick',
            'click here', 'share if you agree', 'before they delete',
            'government doesn\'t want', 'big pharma', 'conspiracy',
            'cover up', 'hidden truth', 'secret revealed'
        ]
    
    def detect_filipino_slang(self, text):
        """Detect Filipino slang and internet language in text"""
        text_lower = text.lower()
        detected_slang = []
        
        for slang, meaning in self.filipino_slang.items():
            if slang in text_lower:
                detected_slang.append({
                    'slang': slang,
                    'meaning': meaning,
                    'position': text_lower.find(slang)
                })
        
        return detected_slang
    
    def detect_sarcasm(self, text):
        """Detect potential sarcasm in text"""
        text_lower = text.lower()
        sarcasm_score = 0
        detected_indicators = []
        
        # Check for sarcasm indicators
        for indicator in self.sarcasm_indicators:
            if indicator in text_lower:
                sarcasm_score += 1
                detected_indicators.append(indicator)
        
        # Check for excessive punctuation (!!!, ???)
        if '!!!' in text or '???' in text:
            sarcasm_score += 1
            detected_indicators.append('excessive punctuation')
        
        # Check for ALL CAPS words
        words = text.split()
        caps_count = sum(1 for word in words if word.isupper() and len(word) > 2)
        if caps_count > 0:
            sarcasm_score += caps_count * 0.5
            detected_indicators.append(f'{caps_count} ALL CAPS words')
        
        # Check for contradictory sentiment
        blob = TextBlob(text)
        sentiment = blob.sentiment.polarity
        
        # If text has positive words but negative context, might be sarcastic
        positive_words = ['great', 'amazing', 'wonderful', 'perfect', 'excellent']
        negative_context = ['but', 'however', 'unfortunately', 'sadly', 'too bad']
        
        has_positive = any(word in text_lower for word in positive_words)
        has_negative_context = any(word in text_lower for word in negative_context)
        
        if has_positive and has_negative_context:
            sarcasm_score += 2
            detected_indicators.append('contradictory sentiment')
        
        return {
            'sarcasm_score': sarcasm_score,
            'is_sarcastic': sarcasm_score >= 2,
            'confidence': min(sarcasm_score / 5, 1.0),
            'indicators': detected_indicators,
            'sentiment_polarity': sentiment
        }
    
    def clean_text(self, text):
        """Clean and normalize text"""
        if not text:
            return ""
        
        # Convert to string if not already
        text = str(text)
        
        # Normalize unicode characters
        text = unicodedata.normalize('NFKD', text)
        
        # Remove URLs
        text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', '', text)
        
        # Remove email addresses
        text = re.sub(r'\S+@\S+', '', text)
        
        # Remove mentions and hashtags
        text = re.sub(r'@\w+|#\w+', '', text)
        
        # Remove extra whitespace
        text = re.sub(r'\s+', ' ', text)
        
        # Remove special characters but keep basic punctuation
        text = re.sub(r'[^\w\s.,!?;:()-]', '', text)
        
        # Convert to lowercase
        text = text.lower()
        
        return text.strip()
    
    def tokenize_and_lemmatize(self, text):
        """Tokenize text and apply lemmatization"""
        try:
            # Tokenize
            tokens = word_tokenize(text)
            
            # Remove stopwords and punctuation
            tokens = [token for token in tokens 
                     if token not in self.stop_words 
                     and token not in string.punctuation
                     and len(token) > 2]
            
            # Lemmatize
            tokens = [self.lemmatizer.lemmatize(token) for token in tokens]
            
            return tokens
        except:
            # Fallback to simple split if NLTK fails
            return [word for word in text.split() if len(word) > 2]
    
    def extract_text_from_url(self, url):
        """Extract text content from a URL"""
        try:
            # Try using newspaper3k first
            article = Article(url)
            article.download()
            article.parse()
            
            if article.text:
                return article.text
            
        except Exception as e:
            print(f"Newspaper3k failed: {e}")
        
        try:
            # Fallback to requests + BeautifulSoup
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            }
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()
            
            soup = BeautifulSoup(response.content, 'html.parser')
            
            # Remove script and style elements
            for script in soup(["script", "style"]):
                script.decompose()
            
            # Get text
            text = soup.get_text()
            
            # Clean up whitespace
            lines = (line.strip() for line in text.splitlines())
            chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
            text = ' '.join(chunk for chunk in chunks if chunk)
            
            return text
            
        except Exception as e:
            print(f"URL extraction failed: {e}")
            return f"Could not extract text from URL: {url}"
    
    def preprocess(self, text, detect_slang=True, detect_sarcasm_flag=True):
        """Main preprocessing function"""
        if not text:
            return {
                'cleaned_text': '',
                'tokens': [],
                'slang_detected': [],
                'sarcasm_analysis': {},
                'fake_indicators': [],
                'original_length': 0,
                'processed_length': 0
            }
        
        original_length = len(text)
        
        # Detect Filipino slang
        slang_detected = []
        if detect_slang:
            slang_detected = self.detect_filipino_slang(text)
        
        # Detect sarcasm
        sarcasm_analysis = {}
        if detect_sarcasm_flag:
            sarcasm_analysis = self.detect_sarcasm(text)
        
        # Detect fake news indicators
        fake_indicators = []
        text_lower = text.lower()
        for indicator in self.fake_news_indicators:
            if indicator in text_lower:
                fake_indicators.append(indicator)
        
        # Clean text
        cleaned_text = self.clean_text(text)
        
        # Tokenize and lemmatize
        tokens = self.tokenize_and_lemmatize(cleaned_text)
        
        # Join tokens back to text
        processed_text = ' '.join(tokens)
        
        return {
            'original_text': text,
            'cleaned_text': cleaned_text,
            'processed_text': processed_text,
            'tokens': tokens,
            'slang_detected': slang_detected,
            'sarcasm_analysis': sarcasm_analysis,
            'fake_indicators': fake_indicators,
            'original_length': original_length,
            'processed_length': len(processed_text),
            'token_count': len(tokens)
        }